{"name": "test_create_double_courier_error", "status": "passed", "description": "Попытка создания двух одинаковых курьеров. Ожидание в ответе кода с сообщением об ошибке", "attachments": [{"name": "stdout", "source": "150693b5-6bbe-418c-bf47-2e810cf19221-attachment.txt", "type": "text/plain"}], "start": 1707327579527, "stop": 1707327580168, "uuid": "8d72d650-59e5-4f29-aec7-045ef1fdc1a6", "historyId": "b7b482dbbc7693c6cf72cc8276b44ac5", "testCaseId": "b7b482dbbc7693c6cf72cc8276b44ac5", "fullName": "tests.test_creating_courier.TestAddCourier#test_create_double_courier_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_creating_courier"}, {"name": "subSuite", "value": "TestAddCourier"}, {"name": "host", "value": "MSK-PC777"}, {"name": "thread", "value": "5500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_creating_courier"}]}